kind: pipeline
type: docker
name: graphql-to

workspace:
  path: /drone

steps:
  - name: build
    image: maven
    commands:
      - mvn clean package
    when:
      branch:
        - master
        - develop
        - feature/*
