kind: pipeline
type: docker
name: graphql-to

steps:
  - name: build
    image: maven
    commands:
      - pwd
      - ls -slag
      - mvn clean package
    when:
      branch:
        - master
        - develop
        - feature/*
