kind: pipeline
type: docker
name: graphql-to

steps:
  - name: build
    image: maven
    commands:
      - cd graphql-to
      - mvn clean package
    when:
      branch:
        - master
        - develop
        - feature/*
